# Game information

GAME_NAME="Spore"

INSTALLER="setup_sporetm_collection_3.1.0.22_gog_v2.hotfix_(86147).exe"

# Assumes default installation path
INSTALLED_GAME_DIR="GOG Games/SPORE/SporebinEP1"

EXECUTABLE="SporeApp.exe"

PREFIX="$HOME/.wine-gog"

WINEDLLOVERRIDES=""

INSTALL_ARGS=""
