# Game information

GAME_NAME="Spore"

ISO_NAME="spore.iso"

INSTALLER="setup_sporetm_collection_3.1.0.29_(77221).exe"

# Assumes default installation path
INSTALLED_GAME_DIR="GOG Games/SPORE/SporebinEP1"

EXECUTABLE="SporeApp.exe"

PREFIX="$HOME/.wine-xp"

MOUNT_POINT="/mnt/retrocd"

WINEDLLOVERRIDES=""

INSTALL_ARGS=""
