# Game information

GAME_NAME="Neef for Speed - Most Wanted (Black Edition)"

INSTALLER="Setup.exe"

# Assumes default installation path
INSTALLED_GAME_DIR="Program Files (x86)/EA GAMES/Need for Speed Most Wanted"

EXECUTABLE="speed.exe"

PREFIX="$HOME/.wine-xp"

WINEDLLOVERRIDES=""

INSTALL_ARGS=""
