# Game information

GAME_NAME="Neef for Speed - Most Wanted (Black Edition)"

ISO_NAME="nfs-most-wanted.iso"

INSTALLER="Setup.exe"

# Assumes default installation path
INSTALLED_GAME_DIR="Program Files (x86)/EA GAMES/Need for Speed Most Wanted"

EXECUTABLE="speed.exe"

PREFIX="$HOME/.wine-xp"

MOUNT_POINT="/mnt/retrocd"

WINEDLLOVERRIDES=""

INSTALL_ARGS=""
