# Game information

GAME_NAME="Worms World Party"

ISO_NAME="worms_world_party.iso"

INSTALLER="AUTORUN.EXE"

# Assumes default installation path
INSTALLED_GAME_DIR="Team17/Worms World Party"

EXECUTABLE="wwp.exe"

PREFIX="$HOME/.wine-xp"

MOUNT_POINT="/mnt/retrocd"

WINEDLLOVERRIDES=""

INSTALL_ARGS=""
