# Game information

GAME_NAME="Heroes 3"

INSTALLER="setup_heroes_of_might_and_magic_3_complete_4.0_(3.2)_gog_0.1_(77075).exe"

# Assumes default installation path
INSTALLED_GAME_DIR="GOG Games/HoMM 3 Complete"

EXECUTABLE="Heroes3_HD.exe"

PREFIX="$HOME/.wine-gog"

WINEDLLOVERRIDES=""

INSTALL_ARGS=""
