# Game information

GAME_NAME="Star Wars - The Phantom Menace"

ISO_NAME="swtpm.iso"

INSTALLER="tpm.exe"

# Assumes default installation path
INSTALLED_GAME_DIR="Program Files/LucasArts/The Phantom Menace"

EXECUTABLE="TPM.EXE"

PREFIX="$HOME/.wine-xp"

MOUNT_POINT="/mnt/retrocd"

WINEDLLOVERRIDES=""

INSTALL_ARGS=""
