# Game information

GAME_NAME="Star Wars - The Phantom Menace"

INSTALLER="tpm.exe"

# Assumes default installation path
INSTALLED_GAME_DIR="Program Files/LucasArts/The Phantom Menace"

EXECUTABLE="TPM.EXE"

PREFIX="$HOME/.wine-xp"

WINEDLLOVERRIDES=""

INSTALL_ARGS=""
